apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fdb-operator.fullname" . }}
  labels:
    {{- include "fdb-operator.labels" . | nindent 4 }}
  {{- with .Values.annotations }}  
spec:
  selector:
    matchLabels: 
    {{- include "fdb-operator.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}


