---
image:
  repository: foundationdb/fdb-kubernetes-operator
  tag: v0.37.0
  pullPolicy: IfNotPresent

initContainers:
  # the way the chart is written now, there's no way to avoid pulling in 6.1 and 6.2 every time, which delays pod startup by about 2min. Until this can
  # be solved more elegantly, just comment out 6.1 and 6.2
  # 6.1:
  #   image:
  #     repository: foundationdb/foundationdb-kubernetes-sidecar
  #     tag: 6.1.13-1
  #     pullPolicy: IfNotPresent
  # 6.2:
  #   image:
  #     repository: foundationdb/foundationdb-kubernetes-sidecar
  #     tag: 6.2.30-1
  #     pullPolicy: IfNotPresent
  6.3:
    image:
      repository: foundationdb/foundationdb-kubernetes-sidecar
      tag: 6.3.13-1
      pullPolicy: IfNotPresent

globalMode:
  enabled: false

replicas: null

imagePullSecrets: []

annotations: {}
podAnnotations: {}
podLabels: {}

serviceAccount:
  create: true
  name: null
  imagePullSecrets: []
  annotations: {}

priorityClassName: null

securityContext:
  runAsUser: 4059
  runAsGroup: 4059
  fsGroup: 4059

containerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
    - all
  readOnlyRootFilesystem: true

nodeSelector: {}

affinity: {}

tolerations: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

initContainersResources:
  limits:
    cpu: 10m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 50Mi

initContainerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
    - all
  readOnlyRootFilesystem: true

podDisruptionBudget:
  create: false
  minAvailable: 1
  maxUnavailable: ""